### PR TITLE
Changes to Streaming API

### PR DESCRIPTION
**Pull request by jthurst01**
Did a few things here:

1. Bumped the API version to support v38.0

2. Removed the logic in fdcstream.js to use the full path of the streaming channel, rather then using just the topic name.  This also meant removing the isSystem parameter from the streaming definition, as it is not longer needed.  The client provides a full path like/topic/MyPushTopic

3. Added support for Durable Streaming and Platform Events.  This needed a change to add a replay ID to the streaming subscription, and change to the Faye Client

### CODE REVIEW

**Comment by kevinohara80** [comment]
This is great and I like it. The only issue is that this is a breaking change. I'll have to schedule this for a major and I'd want to bundle that with some other breaking changes. I should be able to get to that this week.

**Comment by kevinohara80** [comment]
Related: #127

**Comment by marioluissc** [comment]
Hi guys, 
Were those changes in the Streaming API ever committed? If yes, which version?

Thank you!!
Mario

**Comment by kevinohara80** [comment]
@marioluissc No, they haven't been. I'll get a release prepared for this shortly.

**Comment by joseph-ortiz** [comment]
Is this still planned for an upcoming release?

**Comment by adam-short** [comment]
Accidental but rlly need this

**Comment by konthamk** [comment]
> @marioluissc No, they haven't been. I'll get a release prepared for this shortly.

@kevinohara80 Is there any plan to get this released?

Thanks

**Comment by gorugontula** [comment]
It appears that replay functionality is not working from platform events

**Pull request merged**
