### PR TITLE
platform events [stuff__e] support

### PR DESCRIPTION
**Pull request by mshanemc**
Kevin, I wasn't sure which direction to take this...there's so much shared with streaming that I wanted to reuse as much as possible.  So I copied the "put a flag on it" like you had for system topics, but just modified it for events, which move from Beta to GA in summer17.

Let me know if this makes sense, or if you'd rather a completely different function for platform events.

### CODE REVIEW

**Comment by kevinohara80** [comment]
Thanks for the PR. The flag was fine when system topics were introduced but now that there's more than 2 types of streams, we should probably change it. I think what would be better at this point would be to implement a stream `type` property and introduce it as a breaking change in the next major version. Values could be `topic`, `system`, and `event` with `topic` being the default. Would you want to implement that?

**Comment by mshanemc** [comment]
I liked jay's more comprehensive PR for streaming, if you're going the breaking changes route.

Was trying to put something non-breaking for the interim solution.

Shane

On Apr 25, 2017, at 2:09 PM, kevinohara80 <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for the PR. The flag was fine when system topics were introduced but now that there's more than 2 types of streams, we should probably change it. I think what would be better at this point would be to implement a stream type property and introduce it as a breaking change in the next major version. Values could be topic, system, and event with topic being the default. Would you want to implement that?

**Comment by Stwissel** [comment]
I have a patched up fork that does Platform events over at /stwissel/nforce, based on the latest npms

**Comment by kevinohara80** [comment]
I'm going to merge this one for now and come up with a new API in the next major version.

**Pull request merged**
