### PR TITLE
Update lodash dependency version to fix vulnerability

### PR DESCRIPTION
**Pull request by viniciusls**
Update lodash dependency version to fix vulnerability as report in #171

### CODE REVIEW

**Comment by viniciusls** [comment]
@kevinohara80 Hey, could you accept this PR and publish it on NPM please? I want to fix this in my project. Thanks! :)

**Comment by viniciusls** [comment]
@kevinohara80 Any news?

**Comment by srihakum** [comment]
@kevinohara80 can you please review and merge this PR

**Comment by kevinohara80** [comment]
Sorry for the delay, this has been fixed in a release that went out today. Let me know if there are any other issues.

**Pull request closed without merging**
