### PR TITLE
propagate salesforce error details 

### PR DESCRIPTION
**Pull request by pentode**
I ran into an issue with a failing field lookup validation/filter and nforce ate the fields property of the salesforce error.  This PR will allow the fields property to be available to the caller.  Additionally, from my reading of the salesforce documentation, the error will always have a .message property, so that should always be passed to the Error ctor.

### CODE REVIEW

**Comment by kevinohara80** [comment]
Looks good but going from lodash 2 to 3 introduces lazy evaluation so I need to check to make sure the upgrade doesn't break any lodash chains. I'll check it out and merge it if it all works.

**Comment by kevinohara80** [comment]
Looks good. Thanks!

**Comment by kevinohara80** [comment]
Released in 1.3.1

**Comment by pentode** [comment]
Much appreciated.  Thanks for your work on this library.  It's been quite nice to work with.

**Pull request merged**
